apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-chart.fullname" . }}-keycloak
  labels:
    app: keycloak
  {{- include "keycloak-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.type }}
  selector:
    app: keycloak
    {{- include "keycloak-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.keycloak.ports | toYaml | nindent 2 }}
