keycloak:
  keycloak:
    args:
    - start-dev
    env:
      kcHealthEnabled: "true"
      kcProxy: edge
      keycloakAdmin: admin
      keycloakAdminPassword: admin
    image:
      repository: quay.io/keycloak/keycloak
      tag: 26.1.3
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  replicas: 1
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
